SELECT DATE(CONCAT_WS('-', Year, Month, 1)) Date, FLOW1 Flow FROM Turtle WHERE FLOW1 IS NOT NULL
UNION ALL
SELECT DATE(CONCAT_WS('-', Year, Month, 2)) Date, FLOW2 Flow FROM Turtle WHERE FLOW2 IS NOT NULL
UNION ALL
SELECT DATE(CONCAT_WS('-', Year, Month, 3)) Date, FLOW3 Flow FROM Turtle WHERE FLOW3 IS NOT NULL
UNION ALL
SELECT DATE(CONCAT_WS('-', Year, Month, 4)) Date, FLOW4 Flow FROM Turtle WHERE FLOW4 IS NOT NULL
UNION ALL
SELECT DATE(CONCAT_WS('-', Year, Month, 5)) Date, FLOW5 Flow FROM Turtle WHERE FLOW5 IS NOT NULL
UNION ALL
SELECT DATE(CONCAT_WS('-', Year, Month, 6)) Date, FLOW6 Flow FROM Turtle WHERE FLOW6 IS NOT NULL
UNION ALL
SELECT DATE(CONCAT_WS('-', Year, Month, 7)) Date, FLOW7 Flow FROM Turtle WHERE FLOW7 IS NOT NULL
UNION ALL
SELECT DATE(CONCAT_WS('-', Year, Month, 8)) Date, FLOW8 Flow FROM Turtle WHERE FLOW8 IS NOT NULL
UNION ALL
SELECT DATE(CONCAT_WS('-', Year, Month, 9)) Date, FLOW9 Flow FROM Turtle WHERE FLOW9 IS NOT NULL
UNION ALL
SELECT DATE(CONCAT_WS('-', Year, Month, 10)) Date, FLOW10 Flow FROM Turtle WHERE FLOW10 IS NOT NULL
UNION ALL
SELECT DATE(CONCAT_WS('-', Year, Month, 11)) Date, FLOW11 Flow FROM Turtle WHERE FLOW11 IS NOT NULL
UNION ALL
SELECT DATE(CONCAT_WS('-', Year, Month, 12)) Date, FLOW12 Flow FROM Turtle WHERE FLOW12 IS NOT NULL
UNION ALL
SELECT DATE(CONCAT_WS('-', Year, Month, 13)) Date, FLOW13 Flow FROM Turtle WHERE FLOW13 IS NOT NULL
UNION ALL
SELECT DATE(CONCAT_WS('-', Year, Month, 14)) Date, FLOW14 Flow FROM Turtle WHERE FLOW14 IS NOT NULL
UNION ALL
SELECT DATE(CONCAT_WS('-', Year, Month, 15)) Date, FLOW15 Flow FROM Turtle WHERE FLOW15 IS NOT NULL
UNION ALL
SELECT DATE(CONCAT_WS('-', Year, Month, 16)) Date, FLOW16 Flow FROM Turtle WHERE FLOW16 IS NOT NULL
UNION ALL
SELECT DATE(CONCAT_WS('-', Year, Month, 17)) Date, FLOW17 Flow FROM Turtle WHERE FLOW17 IS NOT NULL
UNION ALL
SELECT DATE(CONCAT_WS('-', Year, Month, 18)) Date, FLOW18 Flow FROM Turtle WHERE FLOW18 IS NOT NULL
UNION ALL
SELECT DATE(CONCAT_WS('-', Year, Month, 19)) Date, FLOW19 Flow FROM Turtle WHERE FLOW19 IS NOT NULL
UNION ALL
SELECT DATE(CONCAT_WS('-', Year, Month, 20)) Date, FLOW20 Flow FROM Turtle WHERE FLOW20 IS NOT NULL
UNION ALL
SELECT DATE(CONCAT_WS('-', Year, Month, 21)) Date, FLOW21 Flow FROM Turtle WHERE FLOW21 IS NOT NULL
UNION ALL
SELECT DATE(CONCAT_WS('-', Year, Month, 22)) Date, FLOW22 Flow FROM Turtle WHERE FLOW22 IS NOT NULL
UNION ALL
SELECT DATE(CONCAT_WS('-', Year, Month, 23)) Date, FLOW23 Flow FROM Turtle WHERE FLOW23 IS NOT NULL
UNION ALL
SELECT DATE(CONCAT_WS('-', Year, Month, 24)) Date, FLOW24 Flow FROM Turtle WHERE FLOW24 IS NOT NULL
UNION ALL
SELECT DATE(CONCAT_WS('-', Year, Month, 25)) Date, FLOW25 Flow FROM Turtle WHERE FLOW25 IS NOT NULL
UNION ALL
SELECT DATE(CONCAT_WS('-', Year, Month, 26)) Date, FLOW26 Flow FROM Turtle WHERE FLOW26 IS NOT NULL
UNION ALL
SELECT DATE(CONCAT_WS('-', Year, Month, 27)) Date, FLOW27 Flow FROM Turtle WHERE FLOW27 IS NOT NULL
UNION ALL
SELECT DATE(CONCAT_WS('-', Year, Month, 28)) Date, FLOW28 Flow FROM Turtle WHERE FLOW28 IS NOT NULL
UNION ALL
SELECT DATE(CONCAT_WS('-', Year, Month, 29)) Date, FLOW29 Flow FROM Turtle WHERE FLOW29 IS NOT NULL
UNION ALL
SELECT DATE(CONCAT_WS('-', Year, Month, 30)) Date, FLOW30 Flow FROM Turtle WHERE FLOW30 IS NOT NULL
UNION ALL
SELECT DATE(CONCAT_WS('-', Year, Month, 31)) Date, FLOW31 Flow FROM Turtle WHERE FLOW31 IS NOT NULL AND FLOW31 > 0
ORDER BY Date